-- Bug Tracker SQL setup is split into small parts now.
-- Run these files in order inside Supabase SQL Editor:
--
-- 1. sql/01_extensions_and_enums.sql
-- 2. sql/02_tables.sql
-- 3. sql/03_indexes.sql
-- 4. sql/04_functions_and_triggers.sql
-- 5. sql/05_backfill_profiles.sql
-- 6. sql/06_rls_and_policies.sql
-- 7. sql/07_storage.sql
-- 8. sql/08_leaderboard.sql
-- 9. sql/09_realtime.sql
--
-- Reason:
-- - easier debugging
-- - easier reruns
-- - feature-wise separation
--
-- If one step fails, fix that step and re-run only that file.
